public with sharing class AccountService {
    public AccountService() {
        selectById();
        method1();
        method2();
        method4();

    }

    public void selectById(){
        String str = 'ytest1';
    }

    public void method1(){
        String str = 'ytest1';
    }

    public void method2(){
        String str = 'ytest1';
    }

    public void method4(){
        String str = 'ytest1';
    }

}
